platformName: Android
platformVersion: 7.1.2
deviceName: 127.0.0.1:62001
noRest: False
appPackage: com.tnaot.newspro
appActivity: com.tnaot.news.mctnews.detail.activity.MainActivity
unicodeKeyboard: True
resetKeyboard: True
ip: 127.0.0.1
port: 4723

